name: Build, Push, and Update GitOps

on:
  workflow_dispatch:

  push:
    branches:
      - main
    paths:
      - "app/**"

permissions:
  id-token: write
  contents: write

env:
  AWS_REGION: us-east-2
  ECR_REPOSITORY: devops-tech-challenge-2-app

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v5
        with:
          role-to-assume: arn:aws:iam::220912169334:role/devops-tech-challenge-2-github-actions-role
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push Docker image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build \
            -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG \
            ./app

          docker push \
            $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Update GitOps image tag
        env:
          IMAGE_TAG: ${{ github.sha }}
        run: |
          sed -i "s|tag: \".*\"|tag: \"$IMAGE_TAG\"|" helm/tech-challenge-2/values.yaml

      - name: Commit GitOps update
        env:
          IMAGE_TAG: ${{ github.sha }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add helm/tech-challenge-2/values.yaml
          git commit -m "Update application image to $IMAGE_TAG"
          git push origin main